# Generated by Django 3.2.4 on 2021-07-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='createtodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=None, max_length=120)),
                ('Date', models.DateField(default=None)),
                ('Time', models.TimeField(default=None)),
                ('Description', models.TextField(default=None, max_length=1000)),
                ('History', models.CharField(default=None, max_length=200)),
            ],
        ),
    ]
